-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 09:46:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema west_burger
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `west_burger` ;

-- -----------------------------------------------------
-- Schema west_burger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `west_burger` DEFAULT CHARACTER SET utf8 ;
USE `west_burger` ;

-- -----------------------------------------------------
-- Table `west_burger`.`typeUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`typeUtilisateur` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`typeUtilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUtilisateur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(100) NOT NULL,
  `prenomUtilisateur` VARCHAR(100) NOT NULL,
  `mailUtilisateur` VARCHAR(100) NOT NULL,
  `mdpUtilisateur` VARCHAR(200) NOT NULL,
  `telUtilisateur` VARCHAR(20) NOT NULL,
  `adresseUtilisateur` VARCHAR(100) NOT NULL,
  `codePostalUtilisateur` VARCHAR(5) NOT NULL,
  `villeUtilisateur` VARCHAR(45) NOT NULL,
  `typeUtilisateur_id` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_utilisateur_typeUtilisateur_idx` (`typeUtilisateur_id` ASC),
  CONSTRAINT `fk_utilisateur_typeUtilisateur`
    FOREIGN KEY (`typeUtilisateur_id`)
    REFERENCES `west_burger`.`typeUtilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`boisson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`boisson` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`boisson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomBoisson` VARCHAR(100) NOT NULL,
  `prixBoisson` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`plat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`plat` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`plat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomPlat` VARCHAR(100) NOT NULL,
  `descPlat` VARCHAR(45) NOT NULL,
  `prixPlat` INT NOT NULL,
  `imagePlat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`Accompagnement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`Accompagnement` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`Accompagnement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomAccompagnement` VARCHAR(100) NOT NULL,
  `prixAccompagnement` INT NOT NULL,
  `imageAccompagnement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`menu` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`menu` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomMenu` VARCHAR(100) NOT NULL DEFAULT 'Menu',
  `prix` INT NOT NULL DEFAULT 10,
  `boisson_id` INT NOT NULL,
  `plat_id` INT NULL,
  `Accompagnement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_menu_boisson1_idx` (`boisson_id` ASC),
  INDEX `fk_menu_plat1_idx` (`plat_id` ASC),
  INDEX `fk_menu_Accompagnement1_idx` (`Accompagnement_id` ASC),
  CONSTRAINT `fk_menu_boisson1`
    FOREIGN KEY (`boisson_id`)
    REFERENCES `west_burger`.`boisson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_plat1`
    FOREIGN KEY (`plat_id`)
    REFERENCES `west_burger`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_Accompagnement1`
    FOREIGN KEY (`Accompagnement_id`)
    REFERENCES `west_burger`.`Accompagnement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`dessert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`dessert` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`dessert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomDessert` VARCHAR(100) NOT NULL,
  `prixDessert` INT NOT NULL,
  `imageDessert` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`friture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`friture` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`friture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomFriture` VARCHAR(100) NOT NULL,
  `descFriture` TEXT(500) NOT NULL,
  `prixFriture` INT NOT NULL,
  `imageFriture` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`salade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`salade` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`salade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomSalade` VARCHAR(100) NOT NULL,
  `prixSalade` INT NOT NULL,
  `descSalade` TEXT(500) NOT NULL,
  `imageSalade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`menuSalade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`menuSalade` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`menuSalade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomMenuSalade` VARCHAR(100) NOT NULL DEFAULT 'Menu Salade',
  `prix` INT NOT NULL DEFAULT 10,
  `salade_id` INT NOT NULL,
  `boisson_id` INT NOT NULL,
  `Accompagnement_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_menuSalade_salade1_idx` (`salade_id` ASC),
  INDEX `fk_menuSalade_boisson1_idx` (`boisson_id` ASC),
  INDEX `fk_menuSalade_Accompagnement1_idx` (`Accompagnement_id` ASC),
  CONSTRAINT `fk_menuSalade_salade1`
    FOREIGN KEY (`salade_id`)
    REFERENCES `west_burger`.`salade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuSalade_boisson1`
    FOREIGN KEY (`boisson_id`)
    REFERENCES `west_burger`.`boisson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuSalade_Accompagnement1`
    FOREIGN KEY (`Accompagnement_id`)
    REFERENCES `west_burger`.`Accompagnement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`menuEnfant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`menuEnfant` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`menuEnfant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomMenuEnfant` VARCHAR(100) NOT NULL DEFAULT 'Menu Enfant',
  `prix` INT NOT NULL DEFAULT 10,
  `plat_id` INT NULL,
  `Accompagnement_id` INT NOT NULL,
  `boisson_id` INT NOT NULL DEFAULT 1,
  `dessert_id` INT NOT NULL DEFAULT 1,
  `friture_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_menuEnfant_plat1_idx` (`plat_id` ASC),
  INDEX `fk_menuEnfant_Accompagnement1_idx` (`Accompagnement_id` ASC),
  INDEX `fk_menuEnfant_boisson1_idx` (`boisson_id` ASC),
  INDEX `fk_menuEnfant_dessert1_idx` (`dessert_id` ASC),
  INDEX `fk_menuEnfant_friture1_idx` (`friture_id` ASC),
  CONSTRAINT `fk_menuEnfant_plat1`
    FOREIGN KEY (`plat_id`)
    REFERENCES `west_burger`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuEnfant_Accompagnement1`
    FOREIGN KEY (`Accompagnement_id`)
    REFERENCES `west_burger`.`Accompagnement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuEnfant_boisson1`
    FOREIGN KEY (`boisson_id`)
    REFERENCES `west_burger`.`boisson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuEnfant_dessert1`
    FOREIGN KEY (`dessert_id`)
    REFERENCES `west_burger`.`dessert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuEnfant_friture1`
    FOREIGN KEY (`friture_id`)
    REFERENCES `west_burger`.`friture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`supplements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`supplements` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`supplements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomSupplement` VARCHAR(100) NOT NULL,
  `imageSupplement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `west_burger`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `west_burger`.`panier` ;

CREATE TABLE IF NOT EXISTS `west_burger`.`panier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menu_id` INT UNSIGNED NULL,
  `menuSalade_id` INT NULL,
  `menuEnfant_id` INT NULL,
  `plat_id` INT NULL,
  `friture_id` INT NULL,
  `dessert_id` INT NULL,
  `utilisateur_id` INT NOT NULL,
  `supplements_id` INT NULL,
  `quantite` INT NOT NULL,
  `prix` INT NOT NULL,
  `retrait` VARCHAR(100) NULL,
  `dateCommande` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_panier_menu1_idx` (`menu_id` ASC),
  INDEX `fk_panier_menuSalade1_idx` (`menuSalade_id` ASC),
  INDEX `fk_panier_menuEnfant1_idx` (`menuEnfant_id` ASC),
  INDEX `fk_panier_plat1_idx` (`plat_id` ASC),
  INDEX `fk_panier_utilisateur1_idx` (`utilisateur_id` ASC),
  INDEX `fk_panier_supplements1_idx` (`supplements_id` ASC),
  INDEX `fk_panier_friture1_idx` (`friture_id` ASC),
  INDEX `fk_panier_dessert1_idx` (`dessert_id` ASC),
  CONSTRAINT `fk_panier_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `west_burger`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_menuSalade1`
    FOREIGN KEY (`menuSalade_id`)
    REFERENCES `west_burger`.`menuSalade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_menuEnfant1`
    FOREIGN KEY (`menuEnfant_id`)
    REFERENCES `west_burger`.`menuEnfant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_plat1`
    FOREIGN KEY (`plat_id`)
    REFERENCES `west_burger`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `west_burger`.`utilisateur` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_panier_supplements1`
    FOREIGN KEY (`supplements_id`)
    REFERENCES `west_burger`.`supplements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_friture1`
    FOREIGN KEY (`friture_id`)
    REFERENCES `west_burger`.`friture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_dessert1`
    FOREIGN KEY (`dessert_id`)
    REFERENCES `west_burger`.`dessert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `west_burger`.`typeUtilisateur`
-- -----------------------------------------------------
START TRANSACTION;
USE `west_burger`;
INSERT INTO `west_burger`.`typeUtilisateur` (`id`, `nomTypeUtilisateur`) VALUES (1, 'Utilisateur');
INSERT INTO `west_burger`.`typeUtilisateur` (`id`, `nomTypeUtilisateur`) VALUES (2, 'Administrateur');

COMMIT;

